version: "3.8"

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/mysql-data/todo-app

networks:
  todo-network:
    driver: bridge

services:
  mysql-db:
    image: mysql:latest
    networks:
      - todo-network
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3037:3036
    environment:
      MYSQL_ROOT_PASSWORD: "Root@123"
      MYSQL_DATABASE: "tododb"

  todo-application:
    image: adityahonkalas/todo-application-image:latest
    networks:
      - todo-network
    depends_on:
      - mysql-db
    ports:
      - 8082:8081
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/tododb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Root@123"
